name: Evaldo Junior (InFog)
description: Um blog sobre GNU/Linux, PHP, Python e outras coisas sobre programação, TI e nerdices.
url: http://blog.evaldojunior.com.br
markdown: kramdown
gems: [jekyll-paginate, jekyll-feed]
highlighter: rouge
timezone: America/Sao_Paulo
paginate: 10
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      mainimage: "default.jpg"
  -
    scope:
      path: ""
      type: posts
    values:
      mainimage: "default.jpg"
